debug: false # ?? ?? ???
management.endpoint.web.exposure.include: "*" # ?????? ????? ?? ??? ( ?????? ???? ?? ??? ? ? ??? ? ), ?????

logging:
  level:
    com.fastcampus.boardproject: debug # ? ????? ???? ???? ??? ??? ???
    org.springframework.web.servlet: debug # ??? ?? ???? debug? true? ?? ???? ?? ??? ?? ???? debug? false, request, response ??? ???
    org.hibernate.type.descriptor.sql.BasicBinder: trace # jpa ??? ??? ? ????? ??? ??? ?? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: "un"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # data.sql ?? ??, test? db? ??? ????? ?????? ?? sql ??? ???? ? ?? ??? ??? ? ???
    hibernate.ddl-auto: create # ???? ?? ???? ddl? ??
    show-sql: true # sql ??? ??? ???? ???? ?
    properties:
      hibernate.format_sql: true # ??? ??? ??? ?? ??? ???? ???
      hibernate.default_batch_fetch_size: 100 # ??? ?? ???? ?????? row ?? 10?? ??? 10? ???? ? ?? (n+1 ??) >> 100? ??? ??? ??? ??? ? ? ?? ??
  h2.console.enabled: false # h2 ?? ??? / ????
  sql.init.mode: always # data.sql ?? ?????? Never : ?? X, always : ?? O, Embedded : ??? ????? ??

--- # yaml ??? ---? ???? ???? document? ?? ? ??
spring:
  config.activate.on-profile: testdb # testdb profile? activate ?? ? ??? ???
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
